# Generated by Django 5.2.7 on 2025-10-28 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTipo',
            fields=[
                ('id_documento_tipo', models.CharField(db_column='ID_DOCUMENTO_TIPO', primary_key=True, serialize=False)),
                ('documento_tipo', models.CharField(blank=True, db_column='DOCUMENTO_TIPO', max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.CharField(db_column='ID_PAIS', primary_key=True, serialize=False)),
                ('pais', models.CharField(blank=True, db_column='PAIS', max_length=50)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.CharField(db_column='ID_REGION', primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, db_column='REGION', max_length=50)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='UsuarioTipo',
            fields=[
                ('id_usuario_tipo', models.CharField(db_column='ID_USUARIO_TIPO', primary_key=True, serialize=False)),
                ('usuario_tipo', models.CharField(blank=True, db_column='USUARIO_TIPO', max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo de Usuario',
                'verbose_name_plural': 'Tipos de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(db_column='ID_USUARIO', primary_key=True, serialize=False)),
                ('usuario_nombre', models.CharField(blank=True, db_column='USUARIO_NOMBRE', max_length=50)),
                ('usuario_apellido', models.CharField(blank=True, db_column='USUARIO_APELLIDO', max_length=50)),
                ('telefono', models.CharField(blank=True, db_column='TELEFONO', max_length=20)),
                ('email', models.EmailField(blank=True, db_column='EMAIL', max_length=254)),
                ('direccion', models.CharField(blank=True, db_column='DIRECCION', max_length=100)),
                ('id_pais', models.ForeignKey(db_column='ID_PAIS', on_delete=django.db.models.deletion.CASCADE, to='miapp.pais')),
                ('id_region', models.ForeignKey(db_column='ID_REGION', on_delete=django.db.models.deletion.CASCADE, to='miapp.region')),
                ('id_usuario_tipo', models.ForeignKey(db_column='ID_USUARIO_TIPO', on_delete=django.db.models.deletion.CASCADE, to='miapp.usuariotipo')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['usuario_nombre', 'usuario_apellido'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.CharField(db_column='ID_DOCUMENTO', primary_key=True, serialize=False)),
                ('documento_nombre', models.CharField(blank=True, db_column='DOCUMENTO_NOMBRE', max_length=50)),
                ('id_documento_tipo', models.ForeignKey(blank=True, db_column='ID_DOCUMENTO_TIPO', null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.documentotipo')),
                ('id_usuario', models.ForeignKey(db_column='ID_USUARIO', on_delete=django.db.models.deletion.CASCADE, to='miapp.usuario')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
