# Generated by Django 5.2.7 on 2025-10-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='id_documento',
            field=models.CharField(db_column='ID_DOCUMENTO', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentotipo',
            name='id_documento_tipo',
            field=models.CharField(db_column='ID_DOCUMENTO_TIPO', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pais',
            name='id_pais',
            field=models.CharField(db_column='ID_PAIS', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='id_region',
            field=models.CharField(db_column='ID_REGION', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.CharField(db_column='ID_USUARIO', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuariotipo',
            name='id_usuario_tipo',
            field=models.CharField(db_column='ID_USUARIO_TIPO', max_length=10, primary_key=True, serialize=False),
        ),
    ]
